[package]
name = "ticket-sale-server"
version = "0.1.0"
edition = "2021"

[dependencies]
tiny_http = "0.12"
flume = "0.11"
parking_lot = "0.12.3"
rand = "0.8"
uuid = { version = "1", features = ["v4"] }
ticket-sale-core.workspace = true
ticket-sale-rocket.workspace = true
